// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8TfYJbsR3mbxsCsuKnBH_mJ38-IipPZs',
    appId: '1:480244861524:web:8d3298c2cfa81944523bc1',
    messagingSenderId: '480244861524',
    projectId: 'appinio-restaurant',
    authDomain: 'appinio-restaurant.firebaseapp.com',
    storageBucket: 'appinio-restaurant.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjK8OlDfi9UF9sz8V_UBVhfaKTWTKCILk',
    appId: '1:480244861524:android:86266e98ae924849523bc1',
    messagingSenderId: '480244861524',
    projectId: 'appinio-restaurant',
    storageBucket: 'appinio-restaurant.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDb5OLQ-iQ1UK7nIfWXR7t_QX8GzC-nTc',
    appId: '1:480244861524:ios:44ad7a7822f050df523bc1',
    messagingSenderId: '480244861524',
    projectId: 'appinio-restaurant',
    storageBucket: 'appinio-restaurant.appspot.com',
    iosClientId: '480244861524-lvufmk9s27ee2jrcdbih0ie9qc8u8a5l.apps.googleusercontent.com',
    iosBundleId: 'com.example.appinioRestaurant',
  );
}
